version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11  # or specify your Java version
      #maven: 3.8       # or your Maven version
    commands:
      - echo "Starting Install Phase"
      - echo "Setting up Allure CLI for reporting"
      - curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.zip
      - unzip allure.zip -d /opt/allure-cli
      - export PATH=$PATH:/opt/allure-cli/allure-2.13.8/bin
  pre_build:
    commands:
      - echo "Starting Pre-Build Phase"
      - echo "Cloning repository from GitLab"
      - git clone https://github.com/MyAutomationLabs/LatestCucumberProject.git # replace with your GitLab repo URL
      - cd LatestCucumberProject  # navigate to the project directory
  build:
    commands:
      - echo "Starting Build Phase"
      - echo "Running Maven clean and package"
      - mvn clean package -DskipTests=false
      - echo "Running Maven tests"
      - mvn test
      - mvn allure:report 
  post_build:
    commands:
      - echo "Starting Post-Build Phase"
      - echo "Generating Allure Report"
      - allure generate allure-results --clean -o allure-report
      - aws s3 cp ./target/allure-report s3://codepipeline-ap-southeast-2-166223259325/allure-report --recursive
artifacts:
  files:
    - target/*.jar                # Adjust this based on your packaging type (e.g., .war or .jar)
    - allure-report/**/*           # Allure report files
  discard-paths: yes
