version: '3'

services:
  selenium-hub:
    image: selenium/standalone-chrome:latest
    container_name: flamboyant_tharp
    ports:
      - "4444:4444"

  chrome:
    image: selenium/standalone-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.10.0-20231016
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  # Optional: a service for running your tests
  tests:
    build:
      context: .
      dockerfile: Dockerfile # Define a Dockerfile that installs dependencies and runs your tests
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_REMOTE_URL=http://localhost:4444
    volumes:
      - .:/usr/src/app
